> ### 데이터 청년 캠퍼스
> #### 노재혁

## 통계

- #### 평균 확인

In [24]:
import numpy as np

# np.random.seed(121) 난수생성

avg_ran_list = np.random.randint(100, size=10) # 랜덤한 정수 표본추출
avg = np.mean(avg_ran_list)


print(avg)

56.2


- #### 분산과 표준편차의 차이 확인

In [50]:
# 100배 차이 나는 두 변수
first_num = np.random.choice(200, 5, replace=False)
second_num = first_num / 100

print(np.var(first_num))
print(np.var(second_num))

1707.8399999999997
0.17078399999999996


In [39]:
print(np.std(first_num))
print(np.std(second_num))

49.74977386883281
0.49749773868832814


In [54]:
def standardize(x):
    return (x - np.mean(x) / np.std(x))

print(standardize(first_num))
print(standardize(second_num))

[135.42535096 146.42535096 116.42535096  90.42535096  30.42535096]
[-1.19464904 -1.08464904 -1.38464904 -1.64464904 -2.24464904]


- #### 정규분포난수를 생성하고 평균과 표준편차 계산

In [55]:
n = np.random.randn(1000)

print(np.mean(n))
print(np.std(n))

-0.04712539978382888
0.9975260928014766


## 미분

- #### 2차함수계산

In [56]:
def f(x):
    return x ** 2 + 1

print(f(-2))
print(f(1))

5
2


- #### 미분

In [57]:
def df(a, h):
    return (f(a + h) - f(a)) / h

for h in [1, 1e-1, 1e-2, 1e-3]:
    print([h, df(0, h), df(1, h)])

[1, 1.0, 3.0]
[0.1, 0.10000000000000009, 2.0999999999999996]
[0.01, 0.009999999999998899, 2.010000000000023]
[0.001, 0.0009999999999177334, 2.0009999999999195]


## 행렬

- #### 행렬의 합과 차 계산

In [58]:
A = np.array([[1, 2, 3], [3, 4, 5]])
B = np.array([[3, 4, 5], [4, 5, 6]])

In [59]:
print(A + B)
print(A - B)

[[ 4  6  8]
 [ 7  9 11]]
[[-2 -2 -2]
 [-1 -1 -1]]


- #### 행렬의 곱 계산

In [61]:
A = np.array([[1, 2, 3], [3, 4, 5]])
B = np.array([[3, 4], [4, 5], [5, 6]])

print(A.dot(B))
print(A @ B)

[[26 32]
 [50 62]]
[[26 32]
 [50 62]]


- #### 행렬의 역행렬

In [62]:
A = np.array([[2, 5], [1, 3]])
print(np.linalg.inv(A))

[[ 3. -5.]
 [-1.  2.]]


- #### 행렬식 계산

In [64]:
A = np.array([[2, 5], [1, 3]])
print(np.linalg.det(A))

B = np.array([[1, 4, 2], [3, -1, -2], [-3, 1, 3]])
print(np.linalg.det(B))

1.0
-13.0
